// popup/pages/Create.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { push } from 'svelte-spa-router';
  import { fly } from 'svelte/transition';
  import flyTransition from 'popup/transitions/fly';
	import { _ } from 'popup/i18n';
	import { getRandomSeed } from "popup/backend/phrase";
  import { printMnemonic } from 'lib/utils/printer';
  import wordsStore from 'popup/store/words';

  import SwitchButton from '../components/SwitchButton.svelte';
  import BackBar from '../components/BackBar.svelte';
  import PickButton from '../components/PickButton.svelte';

  let length = 128;
  let words = [];

	$: disabled = words.length < 12;

  const hanldeRandomWords = async() => {
    const seed = await getRandomSeed(length);
    words = seed.split(' ');
  };
  const hanldeSelectNumber = (e) => {
    const value = e.detail;

    length = value ? 256 : 128;

    hanldeRandomWords();
  };
  const hanldeOnContinue = () => {
    wordsStore.set(words);
    push('/verify');
  };
  const handleOnPrint = () => {
    const phrase = words.join(' ');
    const html = printMnemonic(phrase, $_('create.print'));
    const win = window.open('', 'win');
    win.document.write(html);

    setTimeout(() => {
      win.print();
    }, 500);
  };

  onMount(() => {
    hanldeRandomWords();
  });
</script>

<main in:fly={flyTransition.in}>
  <BackBar
    length={3}
    selected={0}
  />
  <h1>
    {$_('create.title')}
  </h1>
  <h3>
    {$_('create.sub_title')}
  </h3>
  <div>
    <SwitchButton
      items={['12', '24']}
      on:select={hanldeSelectNumber}
    />
  </div>
  <div class="wrapper">
    {#each words as w, i}
      <PickButton
        text={w}
        index={i + 1}
      />
    {/each}
  </div>
  <div class="btns">
    <button
      class="secondary"
      on:mouseup={hanldeRandomWords}
    >
      {$_('create.btns.refresh')}
    </button>
    <button
      class="secondary"
      on:mouseup={handleOnPrint}
    >
      {$_('create.btns.print')}
    </button>
    <button
      class="primary"
      disabled={disabled}
      on:mouseup={hanldeOnContinue}
    >
      {$_('create.btns.continue')}
    </button>
  </div>
</main>

<style lang="scss">
	@import "../styles/mixins";
  h1, h3 {
    margin-block-start: 0;
    margin-block-end: 0.2em;
  }
  h1 {
    font-size: 29pt;
  }
  h3 {
    font-size: 16pt;
  }
  main {
		background-color: var(--background-color);
		height: 100vh;

    @include flex-center-top-column;
	}
  div.btns {
    width: 290px;
    @include flex-center-column;

    button {
      margin: 5px;
    }
  }
  div.wrapper {
    margin: 16px;
    overflow-y: scroll;

    height: fit-content;
    max-height: calc(100vh - 30px);
    width: 100%;
    max-width: 450px;

    display: flex;
    flex-wrap: wrap;
    align-items: flex-start;
    justify-content: space-between;
  }
</style>

// src/pages/Create.vue
<template>
  <div :class="b()">
    <UiPanel arrow />
    <SvgInject
      :class="b('logo')"
      :variant="ICON_VARIANTS.zilPayLogo"
    />
    <div :class="b('wrapper')">
      <div>
        <Title :size="SIZE_VARIANS.lg">
          {{ local.CREATE_TITLE }}
        </Title>
        <P :size="SIZE_VARIANS.md">
          {{ local.CREATE_DIS }}
        </P>
      </div>
      <div
        :class="b('reset-icon')"
        @click="refreshWords"
      >
        <SvgInject :variant="ICON_VARIANTS.refresh" />
      </div>
      <div :class="b('words')">
        <Chip
          v-for="(el, index) of wrdsAsArray"
          :key="el.uuid"
          :circle="index + 1"
        >
          {{ el.word }}
        </Chip>
      </div>
      <div :class="b('btns')">
        <Button
          :color="COLOR_VARIANTS.negative"
          block
          round
          uppercase
          @click="prinntWords"
        >
          {{ local.PRINT }}
        </Button>
        <Button
          :color="COLOR_VARIANTS.negative"
          :size="SIZE_VARIANS.md"
          block
          round
          uppercase
          @click="setWords"
        >
          {{ local.CONTINUE }}
        </Button>
      </div>
    </div>
  </div>
</template>

<script>
import { uuid } from 'uuidv4'

import { mapState, mapMutations } from 'vuex'
import uiStore from '@/store/ui'
import walletStore from '@/store/wallet'

import {
  ICON_VARIANTS,
  SIZE_VARIANS,
  COLOR_VARIANTS
} from '@/config'

import Verify from '@/pages/Verify'

import Chip from '@/components/Chip'
import Title from '@/components/Title'
import P from '@/components/P'
import Button from '@/components/Button'
import UiPanel from '@/components/UiPanel'
import Printer from '@/mixins/printer'
import SvgInject from '@/components/SvgInject'

import { Background } from '@/services'

const bgScript = new Background()

export default {
  name: 'Create',
  mixins: [Printer],
  components: {
    Chip,
    P,
    Title,
    Button,
    UiPanel,
    SvgInject
  },
  data() {
    return {
      ICON_VARIANTS,
      SIZE_VARIANS,
      COLOR_VARIANTS,
      words: ''
    }
  },
  computed: {
    ...mapState(uiStore.STORE_NAME, [
      uiStore.STATE_NAMES.local
    ]),

    wrdsAsArray() {
      return this
        .words
        .split(' ')
        .map(word => ({
          word,
          uuid: uuid()
        }))
    }
  },
  methods: {
    ...mapMutations(walletStore.STORE_NAME, [
      walletStore.MUTATIONS_NAMES.setVerifly
    ]),

    setWords() {
      this.setVerifly(this.words)
      this.$router.push({ name: Verify.name })
    },
    async refreshWords() {
      this.words = await bgScript.getRandomMnemonic()
    },
    prinntWords() {
      // Call from Printer mixin.
      this.printSeed()
    }
  },
  mounted() {
    this.refreshWords()
  }
}
</script>

<style lang="scss">
.Create {
  display: flex;
  justify-content: center;
  align-items: center;

  text-align: center;

  background-color: var(--app-background-color);

  &__logo {
    position: absolute;

    width: 50vw;
    height: 50vh;
  }

  &__reset-icon {
    justify-self: right;
    cursor: pointer;
  }

  &__wrapper {
    display: grid;
    justify-items: center;
    grid-template-rows: max-content min-content 100px 50px;

    z-index: 1;
    height: 50vh;

    max-width: 650px;
  }

  &__words {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: space-between;
  }

  &__btns {
    display: flex;
    flex-direction: column;
    justify-content: space-between;

    width: 264px;
    height: 100px;
    margin-top: 100px;
  }
}
</style>
