// popup/components/Button.svelte
<script lang="ts">
  export let width: string = '100%';
  export let height: number = 56;
  export let disabled: boolean = false;
</script>

<button
  {disabled}
  class="button"
  style:width={width}
  style:height={`${height}px`}
>
  <span class="text">
    <slot />
  </span>
</button>

<style lang="scss">
  .button {
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    border: none;
    border-radius: 30px;
    padding: 0 16px;
    background-color: var(--button-background);
    transform-origin: center;
    transition: transform 0.2s cubic-bezier(0.22, 1, 0.36, 1);
    transform: scale(1);
  }

  .button:active:not(:disabled) {
    transform: scale(0.9);
  }

  .button:disabled {
    cursor: not-allowed;
    background-color: color-mix(in srgb, var(--button-background) 50%, transparent);
  }

  .text {
    font-weight: bold;
    font-size: 16px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    color: var(--button-text);
  }

  .button:disabled .text {
    color: color-mix(in srgb, var(--button-text) 50%, transparent);
  }
</style>

// src/components/Button.vue
<template>
  <button
    :class="b({ round, block, size, color })"
    :disabled="disabled"
  >
    <slot />
  </button>
</template>

<script>
import {
  COLOR_VARIANTS,
  SIZE_VARIANS
} from '@/config'

/**
 * @example
 * import { COLOR_VARIANTS, SIZE_VARIANS } from '@/config'
 * <Button
 *   :size="SIZE_VARIANS.md"
 *   :color="COLOR_VARIANTS.primary"
 *   round
 *   block
 *  >
 *    {{ button.text }}
 *  </Button>
 */
export default {
  name: 'Button',
  props: {
    size: {
      type: String,
      default: SIZE_VARIANS.xs
    },
    color: {
      type: String,
      default: COLOR_VARIANTS.primary
    },
    disabled: {
      type: Boolean,
      default: false
    },
    round: {
      type: Boolean,
      default: false
    },
    block: {
      type: Boolean,
      default: false
    }
  }
}
</script>

<style lang="scss">
.Button {
  cursor: pointer;

  box-sizing: border-box;
  font-family: var(--font-family-medium);
  font-style: normal;
  font-weight: 500;
  font-size: 21px;
  line-height: 31px;

  border: 0;
  outline: none;
}

.Button {
  &_round {
    border-radius: .25rem;
  }

  &_block {
    display: block;
    width: 100%;
    height: 100%;
  }
}

.Button {
  &_color-primary {
    background-color: var(--accent-color-primary);
    color: var(--accent-color-white);
  }

  &_color-white {
    background-color: var(--accent-color-white);
    color: var(--accent-color-block);
  }

  &_color-gray {
    background-color: var(--accent-color-gray);
    color: var(--accent-color-white);
  }

  &_color-success {
    background-color: var(--accent-color-success);
    color: var(--accent-color-white);
  }

  &_color-info {
    background-color: var(--accent-color-info);
  }

  &_color-danger {
    background-color: var(--accent-color-danger);
  }

  &_color-transparent {
    background: transparent;
    border: 1px solid var(--accent-color-black);
  }
}

.Button {
  &_size-xs {
    height: var(--size-xs);
  }

  &_size-sm {
    height: var(--size-sm);
  }

  &_size-md {
    height: var(--size-md);
  }

  &_size-lg {
    height: var(--size-lg);
  }
}

.Button {
  &[disabled="disabled"] {
    cursor: unset;
    opacity: 0.5;
  }
}
</style>
