// src/components/DropDown.vue
<template>
  <div :class="b()">
    <a
      v-show="value || show"
      :class="b('close')"
      @click="onDrop"
    />
    <div>
      <a @click="onDrop">
        <SvgInject
          :class="b('arrow')"
          :variant="ICON_VARIANTS.arrow"
        />
      </a>
      <div
        v-show="value || show"
        :class="b('menu')"
      >
        <a @click="onDrop">
          <SvgInject
            :class="b('arrow-inverted')"
            :variant="ICON_VARIANTS.arrow"
          />
        </a>
        <ul :class="b('items')">
          <li
            v-for="(el, index) of items"
            :key="index"
            :class="b('el')"
            @click="onSelected(el, index)"
          >
            <SvgInject
              v-if="el.icon"
              :variant="el.icon"
            />
            <P>
              {{ el.text }}
            </P>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script>
import { ICON_VARIANTS, EVENTS } from '@/config'

import SvgInject from '@/components/SvgInject'
import P from '@/components/P'

export default {
  name: 'DropDown',
  components: {
    SvgInject,
    P
  },
  props: {
    value: {
      type: Boolean,
      default: false
    },
    items: {
      type: Array,
      required: false
    }
  },
  data() {
    return {
      ICON_VARIANTS,

      show: false
    }
  },
  methods: {
    onDrop() {
      this.show = !this.show
      this.$emit(EVENTS.input, !this.value)
    },
    onSelected(el, index) {
      this.$emit(EVENTS.selected, {
        el,
        index
      })
      this.show = !this.show
      this.$emit(EVENTS.input, !this.value)
    }
  }
}
</script>

<style lang="scss">
.DropDown {
  &__arrow,
  &__arrow-inverted {
    path {
      stroke: var(--accent-color-primary);
    }
  }

  &__items {
    display: grid;
    grid-gap: 10px;

    list-style: none;
    padding: 0;
    font-size: 12px;
    line-height: 14px;
    font-weight: 600;
  }

  &__el {
    display: flex;
    align-items: center;
    justify-content: space-between;

    & > svg {
      max-width: 15px;
      max-height: 15px;
    }

    & > .P {
      min-width: 50px;
    }
  }

  &__arrow {
    transform: rotate(270deg);
  }

  &__arrow-inverted {
    transform: rotate(90deg);
  }

  &__menu {
    position: absolute;
    transform: translate(-70%, -24%);

    border-radius: 7px;
    background-color: var(--accent-color-second);
    padding: 10px;
    text-align: right;

    z-index: 3;
  }

  &__close {
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    bottom: 0;
    z-index: 1;

    background-color: var(--opacity-bg-element-2);
    animation: fadeFull 0.2s;
  }
}
</style>

// popup/components/DropDown.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

	import Arrow from './icons/Arrow.svelte';

  const dispatch = createEventDispatcher();

  let show = false;

  export let list = [];

  const hanldeOnSelect = (index: number) => {
    show = false;
    dispatch('select', index);
  };
</script>

<div>
  <div
    class="arrow"
    on:mouseup={() => show = !show}
  >
    <Arrow className="arrow-icon"/>
  </div>
  {#if show}
    <div
      class="close"
      on:mouseup={() => show = false}
    />
    <div class="menu">
      <span
        class="close-arrow-icon"
        on:mouseup={() => show = false}
      >
        <Arrow/>
      </span>
      {#each list as item, i}
        <div
          class="item"
          on:mouseup={() => hanldeOnSelect(i)}
        >
          {item}
        </div>
      {/each}
    </div>
  {/if}
</div>

<style lang="scss">
  @import "../styles";
  div.arrow {
    cursor: pointer;
    margin: 10px;
    transform: rotate(90deg);

    :global(svg.arrow-icon > path) {
      fill: var(--text-color);
    }

    &:hover {
      :global(svg.arrow-icon > path) {
        fill: var(--primary-color);
      }
    }
  }
  div.item {
    color: var(--text-color);
    margin-block-end: 10px;
    font-size: 13px;
    font-family: Demi;
    cursor: pointer;
    &:hover {
      color: var(--primary-color);
    }
  }
  div.close {
    cursor: pointer;
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    backdrop-filter: blur(3px);
    background-color: #0000008f;
  }
  span.close-arrow-icon {
    cursor: pointer;
    transform: rotate(-90deg);
  }
  div.menu {
    position: absolute;
    background-color: var(--notification-color);
    transform: translate(-35%, -56%);
    padding: 5px;
    z-index: 20;
    width: fit-content;
    min-width: 100px;

    align-items: flex-end;
    @include flex-column;
    @include border-radius($default-border-radius);
  }
</style>
